server:
  port: 3333
spring:
  application:
    name: morning
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/sblog?characterEncoding=utf8&useSSL=false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    datasource: 0
    host: 127.0.0.1
    port: 6379
    password: choxsu-redis-pwd
  cache:
    cache-names: people
    caffeine:
      spec: initialCapacity=50,maximumSize=500,expireAfterWrite=10s,refreshAfterWrite=5s
  mail:
    default-encoding: utf-8
    host: smtp.163.com
    password: ---------  # 授权码
    username: choxsu@163.com