server:
  port: 3333
spring:
  application:
    name: morning
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/sblog?characterEncoding=utf8&useSSL=false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    datasource: 0
    host: 192.168.75.129
    port: 5379
    password : choxsu-redis-1
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 0
  mail:
    default-encoding: utf-8
    host: smtp.163.com
    password: yourpassword  # 授权码
    username: choxsu@163.com